description: CVPR2023
target:
  service: amlk8s
  name: itplabrr1cl1

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221015_large_voc_vitb16_prop_head_cosine_160k_bs16_coco171_in130_eval_ade130_thre0.2_weak_structure0.9_detach
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - bash tools/dist_train.sh
        configs/large_voc/vit/prop_cosine_in130/large_voc_vitb16_prop_head_cosine_160k_bs16_coco171_in130_eval_ade130_thre0.2_weak_structure0.9_detach.py
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221015_large_voc_vitb16_prop_head_cosine_160k_bs16_coco171_in130_eval_ade130_thre0.2_weak_structure0.9_detach

  # - name: 20221015_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - bash tools/dist_train.sh
  #       configs/large_voc/vit/linear_in130/large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0.py
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221015_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0

  # - name: 20221015_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - bash tools/dist_train.sh
  #       configs/large_voc/vit/linear_in130/large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2.py
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221015_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2
