description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.1
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/attn4_cosine_in130/vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.1.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.1

  - name: 20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/attn4_cosine_in130/vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.2.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.2

  - name: 20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.3
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/attn4_cosine_in130/vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.3.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.3

  - name: 20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.4
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/attn4_cosine_in130/vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.4.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221017_vitb16_attn4_cosine_160k_bs16_coco171_in130_seed0.4

  # - name: 20221017_large_voc_vitb16_attn3_cosine_160k_bs16_ade150_supervised
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/supervised/large_voc_vitb16_attn3_cosine_160k_bs16_ade150_supervised.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_attn3_cosine_160k_bs16_ade150_supervised

  # - name: 20221017_large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/supervised/large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.0

  # - name: 20221017_large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.2
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/supervised/large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.2.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_prop3_cosine_160k_bs16_ade150_supervised_structure_loss_thre0.2

  # - name: 20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.01
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/attn3_cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.01.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.01

  # - name: 20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.1
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/attn3_cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.1.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.1

  # - name: 20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.2
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/attn3_cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.2.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.2

  # - name: 20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.5
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/attn3_cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.5.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss0.5

  # - name: 20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss1.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/attn3_cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss1.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221017_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_loss_weak_loss1.0
