description: CVPR2023
target:
  service: amlk8s
  name: itplabrr1cl1

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221024_vitb16_cosine_320k_bs16_ade847w_coco171_weakly0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - bash tools/dist_train.sh
        configs/large_voc_v3/vit/baseline_ade847w/vitb16_cosine_320k_bs16_ade847w_coco171_weakly0.2.py
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221024_vitb16_cosine_320k_bs16_ade847w_coco171_weakly0.2

  - name: 20221024_vitb16_cosine_320k_bs16_coco171_in585_ade847w_weakly0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - bash tools/dist_train.sh
        configs/large_voc_v3/vit/cosine_in585_ade847w/vitb16_cosine_320k_bs16_coco171_in585_ade847w_weakly0.2.py
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221024_vitb16_cosine_320k_bs16_coco171_in585_ade847w_weakly0.2