description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_ade150_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_ade150_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_ade150_prior_loss

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_ade150_prior_structure_loss_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_ade150_prior_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_ade150_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_ade847_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_ade847_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_ade847_prior_loss

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_ade847_prior_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_ade847_prior_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_ade847_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_cocostuff_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_cocostuff_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_cocostuff_prior_loss

  # - name: 20221006_large_voc_vitb16_linear_80k_bs16_cocostuff_prior_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_linear_80k_bs16_cocostuff_prior_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_linear_80k_bs16_cocostuff_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade150_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade150_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade150_prior_loss

  - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade150_prior_structure_loss_sing
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade150_prior_structure_loss.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade150_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade150_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade150_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade150_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade847_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade847_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade847_prior_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade847_prior_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade847_prior_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade847_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_ade847_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_ade847_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_ade847_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_prior_structure_loss

  # - name: 20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_structure_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/large_voc_vitb16_cosine_80k_bs16_cocostuff_structure_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221006_large_voc_vitb16_cosine_80k_bs16_cocostuff_structure_loss
