description: CVPR2023
target:
  service: sing
  # name: msroctovc
  name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221013_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss_max10000
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc/vit/linear_in130/large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss_max10000.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss_max10000

  # - name: 20221013_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/linear_in130/large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_linear_160k_bs16_coco171_in130_eval_ade130_prior_loss

  # - name: 20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/propagation/large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0

  # - name: 20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_sep_cls
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/propagation/large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_sep_cls.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_sep_cls

  # - name: 20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_detach
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/propagation/large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_detach.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_prop_head_linear_160k_bs16_coco171_in130_eval_ade130_thre0.0_detach

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight10.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight10.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight10.0

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight5.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight5.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight5.0

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight1.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight1.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_no_neg_in_weight1.0

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.0

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.1
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.1.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.1

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.2

  # - name: 20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.3
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc/vit/cosine_in130/large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.3.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221013_large_voc_vitb16_cosine_160k_bs16_coco171_in130_eval_ade130_prior_structure_loss_thre0.3