description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_baseline/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130

  # - name: 20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/attn2_avg_cosine_in130/vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50

  # - name: 20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup_sing.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/attn2_avg_cosine_in130/vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak
