description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_crop240_avgpool
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_crop240_avgpool.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_crop240_avgpool

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_crop512_avgpool
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_crop512_avgpool.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_crop512_avgpool

  - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_resize0.3_avgpool
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_resize0.3_avgpool.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_resize0.3_avgpool

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_rerun
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_rerun

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_update_img
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_update_img.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_update_img

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_update_sup
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_update_sup.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_update_sup

  # - name: 20221021_vitb16_cosine_160k_bs16_ade150
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_ade150/vitb16_cosine_160k_bs16_ade150.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_ade150

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_append_gt
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_append_gt.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_append_gt

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_memory40
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_memory40.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_memory40

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_max
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_max.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_max

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.05
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.05.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.05

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.15
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.15.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.15

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.3
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_alpha0.3.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.3

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.5
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_alpha0.5.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.5

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.7
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_attn/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_alpha0.7.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_alpha0.7

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.3

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.5

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_avgpool_sup0.7

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.3

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.5

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_sup0.7

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory30

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130_seed0.1_coseg0.2_mean_memory10

  # - name: 20221021_vitb16_cosine_160k_bs16_coco171_in130
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_baseline/vit/cosine_in130/vitb16_cosine_160k_bs16_coco171_in130.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_cosine_160k_bs16_coco171_in130

  # - name: 20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/attn2_avg_cosine_in130/vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50

  # - name: 20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/large_voc_v2/vit/attn2_avg_cosine_in130/vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221021_vitb16_attn2_avg_cosine_160k_bs16_coco171_in130_memory50_weak
