description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221103_vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/coseg_ade847w/vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg

  # - name: 20221103_vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w/vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg

  # - name: 20221103_vitb16_640k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w/vitb16_640k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_640k_wa847_c171_s100_ab0.2_co_ac0.1_mbs20_wu1_fg40_bg

  - name: 20221103_vitb16_320k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/coseg_ade847w_in585/vitb16_320k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0

  - name: 20221103_vitb16_640k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/coseg_ade847w_in585/vitb16_640k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_640k_wa847_c171_i585_s100_ib0.2_ab0.2_co_ic0.1_ac0.1_mbs20_wu1_fg40_bg5_bgt0.35_mse1.0

  # - name: 20221103_vitb16_320k_wa150_c171_ab0.1_ap0.1_pseudo
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/peudo_baseline_ade150w/vitb16_320k_wa150_c171_ab0.1_ap0.1_pseudo.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa150_c171_ab0.1_ap0.1_pseudo

  # - name: 20221103_vitb16_320k_wa150_c171_ab0.1_ap0.2_pseudo
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/peudo_baseline_ade150w/vitb16_320k_wa150_c171_ab0.1_ap0.2_pseudo.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa150_c171_ab0.1_ap0.2_pseudo

  # - name: 20221103_vitb16_320k_wa150_c171_ab0.1_ap0.3_pseudo
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/peudo_baseline_ade150w/vitb16_320k_wa150_c171_ab0.1_ap0.3_pseudo.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa150_c171_ab0.1_ap0.3_pseudo

  # - name: 20221103_vitb16_320k_wa150_c171_ab2.0_wbce
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/bce_baseline_ade150w/vitb16_320k_wa150_c171_ab2.0_wbce.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa150_c171_ab2.0_wbce

  # - name: 20221103_vitb16_320k_wa150_c171_ab4.0_wbce
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/bce_baseline_ade150w/vitb16_320k_wa150_c171_ab4.0_wbce.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221103_vitb16_320k_wa150_c171_ab4.0_wbce

