description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221028_vitb16_320k_wa150_c171_ab0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/baseline_ade150w/vitb16_320k_wa150_c171_ab0.2.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_ab0.2

  - name: 20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/baseline_ade150w_in124/vitb16_320k_wa150_c171_i124_ib0.2_ab0.2.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2

  # - name: 20221028_vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40_bg
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade150w/vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40_bg

  # - name: 20221028_vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade150w/vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_ab0.2_co_mbs20_wu1_fg40

  # - name: 20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade150w_in124/vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0

  # - name: 20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade150w_in124/vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_mbs20_wu1_fg40

  # - name: 20221028_vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40_bg
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w/vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40_bg

  # - name: 20221028_vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w/vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa847_c171_ab0.2_co_mbs20_wu1_fg40

  # - name: 20221028_vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w_in585/vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40_bg5_bgt0.2_mse1.0

  # - name: 20221028_vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade847w_in585/vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221028_vitb16_320k_wa847_c171_i585_ib0.2_ab0.2_co_mbs20_wu1_fg40
