description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

configs/extend_voc/baseline_in11k/vitb16_640k_i11k_c171_s100_ib0.2.py

  - name: 20221107_vitb16_640k_i11k_c171_s100_ib0.2
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/extend_voc/baseline_in11k/vitb16_640k_i11k_c171_s100_ib0.2.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221107_vitb16_640k_i11k_c171_s100_ib0.2

  # - name: 20221107_vitb16_320k_wa847_c171_s300_ab8.0_co_ac4.0_fg20_wbce
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc_bce/bce_coseg_ade847w/vitb16_320k_wa847_c171_s300_ab8.0_co_ac4.0_fg20_wbce.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221107_vitb16_320k_wa847_c171_s300_ab8.0_co_ac4.0_fg20_wbce

  # - name: 20221107_vitb16_80k_a150_base
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/baseline_base/vitb16_80k_a150_base.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221107_vitb16_80k_a150_base

  # - name: 20221107_vitb16_80k_c171_base
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/baseline_base/vitb16_80k_c171_base.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221107_vitb16_80k_c171_base

  # - name: 20221107_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_ic0.1_ac0.0_mbs20_wu1_fg40_bg5_bgt0.35_mse2.0_ms
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/extend_voc/coseg_ade150w_in124/vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_ic0.1_ac0.0_mbs20_wu1_fg40_bg5_bgt0.35_mse2.0.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20221107_vitb16_320k_wa150_c171_i124_ib0.2_ab0.2_co_ic0.1_ac0.0_mbs20_wu1_fg40_bg5_bgt0.35_mse2.0_ms
