description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.3
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.3.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.3

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.29
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.29.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.29

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.28
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.28.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.28

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.27
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.27.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.27

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.26
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.26.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.26

  - name: 20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.25
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup_sing.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/large_voc_v3/vit/context_in124/vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.25.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20221026_vitb16_cosine_320k_bs16_coco171_in124_weakly0.2_seed0.2_full200_context0.25
