description: CVPR2023
target:
  service: sing
  name: msroctovc
  # name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  # - name: 20230128_vitb16_320k_a150_split0_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_ade150/vitb16_320k_a150_split0_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split0_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_a150_split1_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_ade150/vitb16_320k_a150_split1_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split1_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_a150_split2_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_ade150/vitb16_320k_a150_split2_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split2_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_a150_split3_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_ade150/vitb16_320k_a150_split3_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split3_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_c171_split0_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_coco171_10k/vitb16_320k_c171_split0_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_c171_split0_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_c171_split1_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_coco171_10k/vitb16_320k_c171_split1_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_c171_split1_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_c171_split2_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_coco171_10k/vitb16_320k_c171_split2_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_c171_split2_sco_cc0.1_fg1_bg_sing

  # - name: 20230128_vitb16_320k_c171_split3_sco_cc0.1_fg1_bg_sing
  #   sku: G8
  #   sla_tier: basic
  #   execution_mode: basic
  #   priority: high
  #   command:
  #     - set -x; set -e
  #     - pwd; ls; nvidia-smi
  #     - sudo bash aml_setup.sh
  #     - /opt/conda/bin/python -m torch.distributed.launch
  #       --nproc_per_node=8
  #       --master_port=$$MASTER_PORT
  #       tools/train.py
  #       configs/coseg_splits_coco171_10k/vitb16_320k_c171_split3_sco_cc0.1_fg1_bg.py
  #       --launcher pytorch
  #       --auto-resume
  #       --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_c171_split3_sco_cc0.1_fg1_bg_sing

  - name: 20230128_vitb16_320k_wa150_city19_ab0.1
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/baseline_city19_ade150w/vitb16_320k_wa150_city19_ab0.1.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_wa150_city19_ab0.1

# 
# configs/baseline_city19_ade847w/vitb16_320k_wa847_city19_ab0.1.py
# configs/coseg_city19_ade150w/vitb16_320k_wa150_city19_ab0.1_sco_ac0.1_fg1_bg.py
# configs/coseg_city19_ade847w/vitb16_320k_wa847_city19_s100_ab0.2_sco_ac0.1_fg1_bg.py

# configs/baseline_ade150_coco171w/vitb16_320k_wc171_a150_cb0.1.py
# configs/coseg_ade150_coco171w/vitb16_320k_wc171_a150_cb0.1_sco_cc0.1_fg1_bg.py