description: CVPR2023
target:
  service: sing
  # name: msroctovc
  name: msrresrchvc

environment:
  image: zeliu98/pytorch:superbench-nvcr21.05-fixfusedlamb-itp-mmcv-msrest

storage:
  output:
    storage_account_name: zeliuwestus2
    container_name: v-miazhang
    mount_dir: /zeliuwestus2

code:
  local_dir: $CONFIG_DIR/../

jobs:

  - name: 20230128_vitb16_320k_a150_split0_sco_cc0.1_fg1_bg
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/coseg_splits_ade150/vitb16_320k_a150_split0_sco_cc0.1_fg1_bg.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split0_sco_cc0.1_fg1_bg

  - name: 20230128_vitb16_320k_a150_split1_sco_cc0.1_fg1_bg
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/coseg_splits_ade150/vitb16_320k_a150_split1_sco_cc0.1_fg1_bg.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split1_sco_cc0.1_fg1_bg

  - name: 20230128_vitb16_320k_a150_split2_sco_cc0.1_fg1_bg
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/coseg_splits_ade150/vitb16_320k_a150_split2_sco_cc0.1_fg1_bg.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split2_sco_cc0.1_fg1_bg

  - name: 20230128_vitb16_320k_a150_split3_sco_cc0.1_fg1_bg
    sku: G8
    sla_tier: basic
    execution_mode: basic
    priority: high
    command:
      - set -x; set -e
      - pwd; ls; nvidia-smi
      - sudo bash aml_setup.sh
      - /opt/conda/bin/python -m torch.distributed.launch
        --nproc_per_node=8
        --master_port=$$MASTER_PORT
        tools/train.py
        configs/coseg_splits_ade150/vitb16_320k_a150_split3_sco_cc0.1_fg1_bg.py
        --launcher pytorch
        --auto-resume
        --work-dir /zeliuwestus2/output_svlseg/20230128_vitb16_320k_a150_split3_sco_cc0.1_fg1_bg
